[phases.setup]
nixPkgs = ["python311"]
aptPkgs = ["libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libdrm2", "libxkbcommon0", "libxcomposite1", "libxdamage1", "libxfixes3", "libxrandr2", "libgbm1", "libasound2", "libx11-6", "libxcb1", "libxext6"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]

[start]
cmd = "playwright install chromium && python bot.py"
